name: Terraform Plan

on:
  pull_request:
    branches:
     - main
    paths:
      - 'terraform/**'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          soft_fail: true # will only warn with true, it won't fail the pipeline

      - name: TFLint scan
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        working-directory: terraform
        run: |
          tflint --init
          tflint --recursive

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Create tfvars
        working-directory: terraform
        run: |
          cat > terraform.tfvars <<EOF2
          resource_group                = "${{ secrets.TF_RESOURCE_GROUP }}"
          location                      = "${{ secrets.TF_LOCATION }}"
          app_name                      = "${{ secrets.TF_APP_NAME }}"
          env_name                      = "${{ secrets.TF_ENV_NAME }}"
          container_name                = "${{ secrets.TF_CONTAINER_NAME }}"
          image_tag                     = "${{ secrets.TF_IMAGE_TAG }}"
          profile_name                  = "${{ secrets.TF_PROFILE_NAME }}"
          sku_name                      = "${{ secrets.TF_SKU_NAME }}"
          ep_name                       = "${{ secrets.TF_EP_NAME }}"
          fd_group_name                 = "${{ secrets.TF_FD_GROUP_NAME }}"
          fd_origin_name                = "${{ secrets.TF_FD_ORIGIN_NAME }}"
          fd_route_name                 = "${{ secrets.TF_FD_ROUTE_NAME }}"
          custom_name                   = "${{ secrets.TF_CUSTOM_NAME }}"
          custom_domain_name            = "${{ secrets.TF_CUSTOM_DOMAIN_NAME }}"
          virtual_network_name          = "${{ secrets.TF_VNET_NAME }}"
          virtual_network_address_space = "${{ secrets.TF_VNET_ADDRESS_SPACE }}"
          container_app_subnet_name     = "${{ secrets.TF_SUBNET_NAME }}"
          container_app_subnet_prefix   = "${{ secrets.TF_SUBNET_PREFIX }}"
          EOF2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          